apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: day03-building-a-minimal-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
