apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{.Values.nameSpace}}
  labels:
    name: postgres-service
    app: {{.Values.appName}}
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    name: postgres-pod
    app: {{.Values.appName}}