apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{.Values.nameSpace}}
  labels:
    name: redis-service
    app: {{.Values.appName}}
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    name: redis-pod
    app: {{.Values.appName}}