apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: {{.Values.nameSpace}}
  labels:
    name: result-app-service
    app: {{.Values.appName}}
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30005
  selector:
    name: result-app-pod
    app: {{.Values.appName}}