apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  namespace: {{.Values.nameSpace}}
  labels:
    name: voting-app-service
    app: {{.Values.appName}}
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30004
  selector:
    name: voting-app-pod
    app: {{.Values.appName}}